# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'SearchApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Cosmos', '~> 23.0'
  pod 'SwifterSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'RxDataSources'
  # Pods for SearchApp

end
